server:
  port: 8080
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/config/*.xml
spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    suffix: .html
